blog/urls.py
from django.urls import path
from . import views


app_name='blog'
urlpatterns = [
    path('', views.home_page_view, name='home'),        # show the blog posts
    path('blog/', views.home_page_view, name='home'),   # show the blog posts
    path('about-me/', views.about_me_view, name='about-me'),
    path('contact-me/', views.contact_me_view, name='contact-me'),
    path('categorys/', views.category_list_view, name='category-list'),
    path('categorys/<slug:category>', views.category_post_view, name='category-posts'),
    path('search/', views.search_result_view, name='search-result'),
    path('blog/<slug:slug>/', views.detail_page_view, name='post_detail'),
]

src/TWO/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

two/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
        "posts": PostSitemap,
        }

urlpatterns = [
    path('dj-admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
     name='django.contrib.sitemaps.views.sitemap'),
    url(r'^comments/', include('django_comments_xtd.urls')),
]


# serve the static file in debug mode
if settings.DEBUG=="True":
    urlpatterns += static(settings.MEDIA_URL,
                                document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                                document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.utils.text import slugify
from django.contrib.auth.models import User
from django.urls import reverse
from ckeditor.fields import RichTextField
from django.utils.translation import ugettext_lazy as _
from django.template.defaultfilters import truncatechars
from datetime import date


class Category(models.Model):
    """
    Category only have name that posts will link to it
    """
    name = models.CharField(max_length=256, verbose_name="دسته بندی")
    slug = models.SlugField(blank=True, null=True, unique=True, verbose_name="لینک")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:category-posts', args=[self.slug])

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name = _("دسته بندی")
        verbose_name_plural = _("دسته بندی‌ها")
    

class Writer(models.Model):
    """
    define who write the post(post owner)
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name="نام")
    email = models.EmailField(verbose_name="ایمیل")
    username = models.CharField(max_length=128, verbose_name="نام کاربری")
    avatar = models.ImageField(upload_to='avatar/', verbose_name="آواتار")
    bio = models.TextField(verbose_name="بیو") # show in menu bar
    about_me = RichTextField(null=True, blank=True, verbose_name="درباره من")  # show in about me page
    # user be able to add Instagram, Twitter, Youtube, Telegram link

    def __str__(self):
        return self.username

    class Meta:
        verbose_name = _("نویسنده")
        verbose_name_plural = _("نویسنده ها")


class Post(models.Model):
    """
    blog articles 
    """
    STATUS = {
        ('d', 'پیش‌نویس'),
        ('p', 'منتشر شده'),
    }
    title = models.CharField(max_length=256, verbose_name="عنوان")
    slug = models.SlugField(verbose_name="لینک")
    thumbnail = models.ImageField(
        upload_to='uploads/%Y/%m/%d/', null=True, blank=True, verbose_name="عکس")
    content = RichTextField(verbose_name="محتوا")
    category = models.ManyToManyField(Category, verbose_name="دسته بندی")
    keywords=models.CharField(max_length=1024, verbose_name="کلمات کلیدی", default="وبلاگ امید,")
    pub_date = models.DateTimeField(default=timezone.now, verbose_name="تاریخ")
    owner = models.ForeignKey(Writer, on_delete=models.CASCADE, verbose_name="نویسنده")
    status = models.CharField(max_length=1, choices=STATUS, default='d', verbose_name="وضعیت")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        """Return absolute url of post"""
        return reverse('blog:post_detail', args=[self.slug])

    @property
    def description(self):
        """Short description of post"""
        return truncatechars(self.content, 100)

    @property
    def passed_time_since_publish(self):
        """Calculate the passed days, weeks, months, years since article published"""
        today = date.today()
        passed_days = str(today - self.pub_date.date()).split(',', 1)[0].split(' ', 1)[0]
        
        if self.pub_date.date() == date.today():
            return "امروز"
        elif self.pub_date.date() < date.today():
            if int(passed_days) < 7:
                return f"{passed_days} روز قبل"
            if int(passed_days) < 30:
                passed_weeks = round(int(passed_days) / 7)
                return f"{passed_weeks} هفته قبل"
            elif int(passed_days) < 355 and int(passed_days) > 30:
                passed_months = round(int(passed_days) / 30)
                return f"{passed_months} ماه قبل"
            elif int(passed_days) > 355:
                passed_years = round(int(passed_days) / 355)
                return f"{passed_years} سال قبل"

    class Meta:
        verbose_name = _("پست")
        verbose_name_plural = _("پست ها")

comments/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from django_comments_xtd.forms import XtdCommentForm
from django_comments_xtd.models import TmpXtdComment


class CommentForm(XtdCommentForm):
    """Customized comment form for django comment xtd"""
    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['name'].label = _("نام")
        self.fields['name'].widget = forms.TextInput(
            attrs={'placeholder': _('نام (الزامی)'), 'class': 'form-control'})
        self.fields['email'].label = _("ایمیل")
        self.fields['email'].help_text = _(" ")
        self.fields['email'].widget = forms.TextInput(
            attrs={'placeholder': _('آدرس ایمیل (الزامی'), 'class': 'form-control'})

        self.fields['url'].label = _("وبسایت")
        self.fields['url'].required = False
        self.fields['url'].widget = forms.TextInput(attrs={
                'placeholder': _('آدرس وبسایت شما (اختیاری)'),
                'class': 'form-control'})

        self.fields['comment'].widget = forms.Textarea(
            attrs={'placeholder': _('کامنت شما'), 'class': 'form-control', 'style': 'height: 100px;'})

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from django.db.models import Q
from .models import Post, Category


def home_page_view(request):
    """Home Page"""
    posts = Post.objects.filter(status='p').order_by('-pub_date')
    paginator = Paginator(posts, 5)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'posts': posts,
    }
    return render(request, 'blog/index.html', context)


def detail_page_view(request, slug):
    """Detail Page"""
    obj = Post.objects.filter(status='p')
    post = get_object_or_404(obj, slug=slug)
    context = {
        'post': post,
    }
    return render(request, 'blog/blog-post.html', context)


def category_list_view(request):
    category_list = Category.objects.all()

    context = {
        'categorys': category_list,
    }
    return render(request, 'blog/category-list.html', context)


def category_post_view(request, category):
    posts = get_object_or_404(Category, slug=category).post_set.filter(status='p').order_by('-pub_date')

    context = {
        'posts': posts,
        'category': Category.objects.get(slug=category),
    }
    return render(request, 'blog/category-post.html', context)


def search_result_view(request):
    """ serach for articles and return the results"""
    search_query = request.GET.get('query')
    posts = Post.objects.filter(Q(title__icontains=search_query) | Q(content__icontains=search_query))

    context = {
        'posts': posts,
        'search_query': request.GET.get('query'),

    }
    return render(request, 'blog/search-result.html', context)


def about_me_view(request):
    """about me page"""
    return render(request, 'blog/about-me.html')


def contact_me_view(request):
    """contact page"""
    return render(request, 'blog/contact-me.html')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <title>{% block title %}{% endblock title %}</title>
    
    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{% block description %}{% endblock description %}">
    <meta name="author" content="امید محمدی">    
    <meta name="keywords" content="{% block keywords %}{% endblock keywords%}">
    
    <!-- FontAwesome JS-->
     <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" data-auto-a11y="true" ></script>
    
    <!-- Theme CSS -->  
    <link id="theme-style" rel="stylesheet" href="{% static 'blog/css/style.css' %}">

    <link rel="icon" href="{% static 'favicon.ico' %}">

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-YB3DHMY3DD"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-YB3DHMY3DD');
    </script>
    <!-- highlight.js-->
    <link rel="stylesheet" 
    href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/10.0.3/styles/default.min.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/10.0.3/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
    <!-- highlight.js -->
</head> 

<body>
    <header class="header text-center">	    
	    <h1 class="blog-name pt-lg-4 mb-0"><a class="no-text-decoration" href="{% url 'blog:home' %}">تک ویت امید</a></h1>
        
	    <nav class="navbar navbar-expand-lg navbar-dark" >
           
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
                        <div class="animated-icon"><span></span><span></span><span></span><span></span></div>
			</button>

			<div id="navigation" class="collapse navbar-collapse flex-column" >

				<div class="profile-section pt-3 pt-lg-0">
                  <img class="profile-image mb-3 rounded-circle mx-auto" src="{% static 'avatar/profile.jpg' %}" alt="image" >			


                  <div class="bio mb-3">{% if writer_info %}{{ writer_info.bio }}{% endif %}</div><!--//bio-->
					<ul class="social-list list-inline py-3 mx-auto">
			            <li class="list-inline-item"><a href="https://twitter.com/techwithomid" target="_blank"><i class="fab fa-twitter fa-fw"></i></a></li>
			            
			            <li class="list-inline-item"><a href="https://instagram.com/techwithomid" target="_blank"><i class="fab fa-instagram fa-fw"></i></a></li>
			            
			            <li class="list-inline-item"><a href="https://github.com/techwithomid" target="_blank"><i class="fab fa-github-alt fa-fw"></i></a></li>
			            <li class="list-inline-item"><a href="https://t.me/techwithomid" target="_blank"><i class="fab fa-telegram fa-fw"></i></a></li>
			            
			            <li class="list-inline-item"></li>
			        </ul><!--//social-list-->
			        <hr> 
				</div><!--//profile-section-->
				
				<ul class="navbar-nav flex-column text-start">
					<li class="nav-item">
					    <a class="nav-link"  href="{% url 'blog:home' %}"><i class="fas fa-home fa-fw me-2"></i>  بلاگ<span class="sr-only">(current)</span></a>
					</li>

					<li class="nav-item">
					    <a class="nav-link"  href="{% url 'blog:category-list' %}"><i class="fas fa-bookmark fa-fw me-2"></i>  دسته‌بندی<span class="sr-only">(current)</span></a>
					</li>

					<li class="nav-item">
					    <a class="nav-link" href="{% url 'blog:about-me' %}"><i class="fas fa-user fa-fw me-2"></i> درباره من</a>
					</li>

					<li class="nav-item">
					    <a class="nav-link"  href="{% url 'blog:contact-me' %}"><i class=" fas fa-envelope fa-fw me-2"></i>  ارتباط با من</a>
					</li>
				</ul>
				
			</div>
		</nav>
    </header>
    
    <div class="main-wrapper">
            {% block search %}
            {% endblock search %}

        <section id="main-section" class="blog-list px-3 py-5 p-md-5">
            <button type="button" class="btn btn-floating btn-lg" id="btn-back-to-top">
              <i class="fas fa-arrow-up"></i>
            </button>

                {% block content %}
                {% endblock content %}

        </section>
    </div><!--//main-wrapper-->

	<footer class="footer py-2 text-center theme-bg-dark">
		<small class="copyright">تمامی حقوق برای سایت <a href="{% url 'blog:home' %}">«TechWithOmid»</a> محفوظ است.</small>
	</footer>
       
    <!-- Javascript -->          
	<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-W8fXfP3gkOKtndU4JGtKDvXbO53Wy8SZCQHczT5FMiiqmQfUpWbYdTil/SxwZgAN" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js" integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/" crossorigin="anonymous"></script>
    <script>

        // animated menu 
        document.querySelector('.navbar-toggler').addEventListener('click', function () {

        document.querySelector('.animated-icon').classList.toggle('open');
        });


        // scroll back to top
        //Get the button
        let mybutton = document.getElementById("btn-back-to-top");

        // When the user scrolls down 20px from the top of the document, show the button
        window.onscroll = function () {
          scrollFunction();
        };

        function scrollFunction() {
          if (
            document.body.scrollTop > 20 ||
            document.documentElement.scrollTop > 20
          ) {
            mybutton.style.display = "block";
          } else {
            mybutton.style.display = "none";
          }
        }
        // When the user clicks on the button, scroll to the top of the document
        mybutton.addEventListener("click", backToTop);

        function backToTop() {
          document.body.scrollTop = 0;
          document.documentElement.scrollTop = 0;
        }

    </script>
	
</body>
</html> 

templates/blog/about-me.html
{% extends '../base.html' %}


{% block keywords %}امید محمدی, درباره امید محمدی,{% endblock keywords%}
{% block description %}{{writer_info.bio|striptags|truncatechars:150}}{% endblock description %}
{% block title %}درباره‌ی من{% endblock title %}
{% block content %}
	    
	    <article class="blog-post px-3 py-5 p-md-5">
		    <div class="container single-col-max-width">
			    <header class="blog-post-header">
				    <h2 class="title mb-2">درباره‌ی من </h2>
			    </header>
			    
			    <div class="blog-post-body">{{writer_info.about_me|safe}}</div>
				    
		    </div><!--//container-->
	    </article>
	    

    
{% endblock content %}

templates/blog/category-list.html
{% extends '../base.html' %}


{% block keywords %}امید محمدی, درباره امید محمدی,{% endblock keywords%}
{% block title %}دسته بندی‌ها{% endblock title %}
{% block content %}
<div class="container">
<h1 class="title text-center">دسته بندی‌ها</h1>
    <div class="row justify-content-evenly">
          {% for category in categorys %}
            <div class="col-auto m-5">
              <a class="bg-light p-2 h3" href="{{ category.get_absolute_url }}">{{ category.name }}</a>
            </div>
          {% endfor %}
    </div>
</div>
{% endblock %}

templates/blog/category-post.html
{% extends '../base.html' %}

{% block keywords %}امید محمدی, درباره امید محمدی,{% endblock keywords%}
{% block title %}دسته بندی: {{ category.name }} {% endblock title %}
{% block search %}
        <section id="search-section" class="cta-section py-5">
            <div class="container text-center single-col-max-width">
                <div class="single-form-max-width pt-3 mx-auto">
                    <form class="signup-form row g-2 g-lg-2 align-items-center" method="GET" action="{% url 'blog:search-result' %}">
                        <div class="col-9">
                            <input type="search" id="search" name="query" class="form-control me-md-1" placeholder="جستجو در بین مقالات">
                        </div>
                        <div class="col-2">
                            <button type="submit" class="btn btn-primary"><i class="fas fa-search"></i></button>
                        </div>
                    </form><!--//signup-form-->
                </div><!--//single-form-max-width-->
            </div><!--//container-->
        </section>
{% endblock search %}

{% block content %}
    <section class="blog-list px-3 py-5 p-md-5">
        <div class="container single-col-max-width">

        {% if posts %}
            {% for post in posts %}
                <div class="item mb-5">
                    <div class="row g-3 g-xl-0">
                        {% if post.thumbnail %}
                            <div class="col-2 col-xl-3">
                                <img class="img-fluid post-thumb " src="{{post.thumbnail.url}}" alt="image">
                            </div>
                        {% endif %}
                        <div class="col">
                            <h3 class="title mb-1"><a class="text-link" href="{{ post.get_absolute_url }}">{{post.title}}</a></h3>
                            <div class="meta mb-1"><span class="date">{{ post.passed_time_since_publish  }}</span></div>
                            <div class="intro">{{post.description|truncatechars:256|safe}}</div>
                            <a class="text-link" href="{{post.slug}}">بیشتر &larr;</a>
                        </div><!--//col-->
                    </div><!--//row-->
                </div><!--//item-->
                <hr>
            {% endfor %}


            <nav class="blog-nav nav nav-justified my-5">
                {% if page_obj.has_previous %}
                    <a class="nav-link-next m-1 nav-item nav-link rounded" href="?page={{ page_obj.previous_page_number }}">قبلی<i class="arrow-next fas fa-long-arrow-alt-right"></i></a>
                    <a class="nav-link-prev bg-light disabled m-1 nav-item nav-link rounded" href="#">بعدی<i class="arrow-prev fas fa-long-arrow-alt-left"></i></a>
                {% endif %}

                {% if page_obj.has_next %}
                    <a class="nav-link-next bg-light disabled m-1 nav-item nav-link rounded" href="#">قبلی<i class="arrow-next fas fa-long-arrow-alt-right"></i></a>
                    <a class="nav-link-prev m-1 nav-item nav-link rounded" href="?page={{ page_obj.next_page_number }}">بعدی<i class="arrow-prev fas fa-long-arrow-alt-left"></i></a>
                {% endif %}
            </nav>
        {% else %}
                <div class="item mb-5">
                    <div class="row g-3 g-xl-0">
                        <div class="col">
                            <h3 class="title m-5">پستی وجود ندارد.</h3>
                            <div class="intro">فعلابرای این دسته‌بندی پستی وجود ندارد.</div>
                        </div><!--//col-->
                    </div><!--//row-->
                </div><!--//item-->
        {% endif %}

        </div>
    </section>

{% endblock content %}

templates/blog/index.html
{% extends '../base.html' %}

{% block keywords %}امید محمدی, درباره امید محمدی,وبلاگ امید محمدی, techwithomid,{% endblock keywords%}
{% block description %}وبلاگ امید محمدی, وبلاگی درمورد برنامه نویسی و تکنولوژی{% endblock description %}
{% block title %}TechWithOmid | صفحه اصلی{% endblock title %}

{% block search %}
        <section id="search-section" class="cta-section py-5">
		    <div class="container text-center single-col-max-width">
			    <div class="single-form-max-width pt-3 mx-auto">
				    <form class="signup-form row g-2 g-lg-2 align-items-center" method="GET" action="{% url 'blog:search-result' %}">
	                    <div class="col-9">
	                        <input type="search" id="search" name="query" class="form-control me-md-1" placeholder="جستجو در بین مقالات">
	                    </div>
	                    <div class="col-2">
	                        <button type="submit" class="btn btn-primary"><i class="fas fa-search"></i></button>
	                    </div>
	                </form><!--//signup-form-->
			    </div><!--//single-form-max-width-->
		    </div><!--//container-->
        </section>
{% endblock search %}

{% block content %}
	    <section class="blog-list px-3 py-5 p-md-5">
		    <div class="container single-col-max-width">

				{% for post in page_obj %}
			    <div class="item mb-5">
				    <div class="row g-3 g-xl-0">
						{% if post.thumbnail %}
							<div class="col-2 col-xl-3">
                                <img class="img-fluid post-thumb " src="{{post.thumbnail.url}}" alt="{{post.title}}">
							</div>
						{% endif %}
					    <div class="col">
						    <h1 class="title mb-1"><a class="text-link" href="{{ post.get_absolute_url }}">{{post.title}}</a></h1>
                            <div class="meta mb-1"><span class="date">{{ post.passed_time_since_publish }} | {% for category in post.category.all %} <a href="{{category.get_absolute_url}}">{{ category.name }}</a> {% endfor %}</span></div>
						    <div class="intro">{{post.content|truncatechars:256|safe}}</div>
						    <a class="text-link" href="{{post.get_absolute_url}}">بیشتر &larr;</a>
					    </div><!--//col-->
				    </div><!--//row-->
			    </div><!--//item-->
				<hr>
				{% endfor %}
			    
			    

                {% if posts|length < 5 %}
                                            
                {% else %}
                <nav aria-label="Page navigation">
                  <ul class="pagination justify-content-center pagination-dark">
                    {% if page_obj.has_previous%}
                    <li class="page-item active mx-1">
                        <a class="page-link rounded" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                      </a>
                    </li>
                    {% else %}
                    <li class="page-item disabled mx-1">
                      <a class="page-link rounded" href="" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                      </a>
                    </li>
                    {% endif %}

                    <li class="page-item mx-1 disabled"><a class="page-link rounded" href="">{{ page_obj.number }} از {{ page_obj.paginator.num_pages }}</a></li>

                    {% if page_obj.has_next%}
                    <li class="page-item active mx-1">
                        <a class="page-link rounded" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                      </a>
                    </li>
                    {%else%}
                    <li class="page-item disabled mx-1">
                      <a class="page-link rounded" href="" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                      </a>
                    </li>
                    {% endif %}
                  </ul>
                </nav>
                {% endif %}
				
		    </div>
	    </section>

{% endblock content %}

templates/blog/search-result.html
{% extends '../base.html' %}

{% block keywords %}امید محمدی, درباره امید محمدی,{% endblock keywords%}
{% block title %}نتایج برای: {{search_query}}{% endblock title %}
{% block search %}
        <section id="search-section" class="cta-section py-5">
		    <div class="container text-center single-col-max-width">
			    <div class="single-form-max-width pt-3 mx-auto">
				    <form class="signup-form row g-2 g-lg-2 align-items-center" method="GET" action="{% url 'blog:search-result' %}">
	                    <div class="col-9">
	                        <input type="search" id="search" name="query" class="form-control me-md-1" placeholder="جستجو در بین مقالات">
	                    </div>
	                    <div class="col-2">
	                        <button type="submit" class="btn btn-primary"><i class="fas fa-search"></i></button>
	                    </div>
	                </form><!--//signup-form-->
			    </div><!--//single-form-max-width-->
		    </div><!--//container-->
        </section>
{% endblock search %}

{% block content %}
	    <section class="blog-list px-3 py-5 p-md-5">
		    <div class="container single-col-max-width">

                {% if posts %}
                    {% for post in posts %}
                    <div class="item mb-5">
                        <div class="row g-3 g-xl-0">
                            {% if post.thumbnail %}
                                <div class="col-2 col-xl-3">
                                    <img class="img-fluid post-thumb " src="{{post.thumbnail.url}}" alt="image">
                                </div>
                            {% endif %}
                            <div class="col">
                                <h3 class="title mb-1"><a class="text-link" href="{{ post.get_absolute_url }}">{{post.title}}</a></h3>
                                                        <div class="meta mb-1"><span class="date">{{ post.passed_time_since_publish  }} | {% for category in post.category.all %} <a href="{{category.get_absolute_url}}">{{ category.name }}</a> {% endfor %}</span></div>
                                <div class="intro">{{post.description|truncatechars:256|safe}}</div>
                                <a class="text-link" href="{{post.slug}}">بیشتر &larr;</a>
                            </div><!--//col-->
                        </div><!--//row-->
                    </div><!--//item-->
                    <hr>
                    {% endfor %}
                {% else %}
                    <div class="item m-5">
                        <h3 class="title">نتیجه‌ای برای این عبارت پیدا نشد.</h3>
                        <p>اگه چیزی که پیدا نمی‌کنی میتونی بهم از <a href="{% url 'blog:contact-me' %}">اینجا</a> بهم اطلاع بدی تا درموردش بنویسم :)</p>
                    </div>
                    <br/>
                    <br/>
                {% endif %}
				
		    </div>
	    </section>

{% endblock content %}

templates/comments/form.html
{% load i18n %}
{% load comments %}

<form method="POST" action="{% comment_form_target %}" class="form-horizontal">
  {% csrf_token %}
  <fieldset>
    <input type="hidden" name="next" value="{% url 'comments-xtd-sent' %}"/>

    {% for field in form %}
      {% if field.is_hidden %}<div>{{ field }}</div>{% endif %}
    {% endfor %}

    <div style="display:none">{{ form.honeypot }}</div>

    <div class="form-group {% if 'title' in form.errors %}has-error{% endif %}">
      <label for="id_title" class="control-label col-lg-3 col-md-3">
        
      </label>
      <div class="col-lg-7 col-md-7">
        {{ form.title }}
      </div>
    </div>

    <div class="form-group {% if 'comment' in form.errors %}has-error{% endif %}">
      <div class="col-lg-offset-1 col-md-offset-1 col-lg-12 col-md-12">
        {{ form.comment }}
      </div>
    </div>

    {% if not request.user.is_authenticated %}
        <div class="row">
            <div class="col {% if 'name' in form.errors %}has-error{% endif %}">
              <label for="id_name" class="control-label col-lg-3 col-md-3">
                {{ form.name.label }}
              </label>
                {{ form.name }}
            </div>
            <div class="col {% if 'email' in form.errors %}has-error{% endif %}">
              <label for="id_email" class="control-label col-lg-3 col-md-3">
                {{ form.email.label }}
              </label>
                {{ form.email }}
                <span class="help-block">{{ form.email.help_text }}</span>
            </div>
        </div>

    <div class="form-group {% if 'url' in form.errors %}has-error{% endif %}">
      <label for="id_url" class="control-label col-lg-3 col-md-3">
         {{ form.url.label }}
      </label>
      <div class="col-lg-6 col-md-6">
        {{ form.url }}
      </div>
    </div>
    {% endif %}
  </fieldset>

  <div class="form-group">
    <div class="col-lg-offset-3 col-md-offset-3 col-lg-7 col-md-7 mt-2">
      <input type="submit" name="post" value="ارسال" class="btn btn-primary" />
    </div>
  </div>
</form>